"""create incidents table

Revision ID: db7b3d708288
Revises: 
Create Date: 2026-09-09 11:15:15.348107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db7b3d708288'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'occurred_at', 'lat', 'lng', name='uq_incident_source_time_location')
    )
    op.create_index('ix_incidents_category', 'incidents', ['category'], unique=False)
    op.create_index('ix_incidents_occurred_at', 'incidents', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_incidents_source_id'), 'incidents', ['source_id'], unique=False)
    op.create_index('ix_incidents_state', 'incidents', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incidents_state', table_name='incidents')
    op.drop_index(op.f('ix_incidents_source_id'), table_name='incidents')
    op.drop_index('ix_incidents_occurred_at', table_name='incidents')
    op.drop_index('ix_incidents_category', table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
